/// @function script()
/// @description default
/// @param {type} param first parameter
function create_hint_map(){
	/* HORIZONTAL (RIGHT TO LEFT) */
	var i = 0
	hint_map[? 1] = "i1" + string(i) + "j1" + string(1) + "i2" + string(i) + "j2" + string(0)
	hint_map[? 2] = "i1" + string(i) + "j1" + string(2) + "i2" + string(i) + "j2" + string(1)
	hint_map[? 3] = "i1" + string(i) + "j1" + string(3) + "i2" + string(i) + "j2" + string(2)
	hint_map[? 4] = "i1" + string(i) + "j1" + string(4) + "i2" + string(i) + "j2" + string(3)
	hint_map[? 5] = "i1" + string(i) + "j1" + string(5) + "i2" + string(i) + "j2" + string(4)
	hint_map[? 6] = "i1" + string(i) + "j1" + string(6) + "i2" + string(i) + "j2" + string(5)
	hint_map[? 7] = "i1" + string(i) + "j1" + string(7) + "i2" + string(i) + "j2" + string(6)
	i++
	hint_map[? 9] = "i1" + string(i) + "j1" + string(1) + "i2" + string(i) + "j2" + string(0)
	hint_map[? 10] = "i1" + string(i) + "j1" + string(2) + "i2" + string(i) + "j2" + string(1)
	hint_map[? 11] = "i1" + string(i) + "j1" + string(3) + "i2" + string(i) + "j2" + string(2)
	hint_map[? 12] = "i1" + string(i) + "j1" + string(4) + "i2" + string(i) + "j2" + string(3)
	hint_map[? 13] = "i1" + string(i) + "j1" + string(5) + "i2" + string(i) + "j2" + string(4)
	hint_map[? 14] = "i1" + string(i) + "j1" + string(6) + "i2" + string(i) + "j2" + string(5)
	hint_map[? 15] = "i1" + string(i) + "j1" + string(7) + "i2" + string(i) + "j2" + string(6)
	i++
	hint_map[? 17] = "i1" + string(i) + "j1" + string(1) + "i2" + string(i) + "j2" + string(0)
	hint_map[? 18] = "i1" + string(i) + "j1" + string(2) + "i2" + string(i) + "j2" + string(1)
	hint_map[? 19] = "i1" + string(i) + "j1" + string(3) + "i2" + string(i) + "j2" + string(2)
	hint_map[? 20] = "i1" + string(i) + "j1" + string(4) + "i2" + string(i) + "j2" + string(3)
	hint_map[? 21] = "i1" + string(i) + "j1" + string(5) + "i2" + string(i) + "j2" + string(4)
	hint_map[? 22] = "i1" + string(i) + "j1" + string(6) + "i2" + string(i) + "j2" + string(5)
	hint_map[? 23] = "i1" + string(i) + "j1" + string(7) + "i2" + string(i) + "j2" + string(6)
	i++
	hint_map[? 25] = "i1" + string(i) + "j1" + string(1) + "i2" + string(i) + "j2" + string(0)
	hint_map[? 26] = "i1" + string(i) + "j1" + string(2) + "i2" + string(i) + "j2" + string(1)
	hint_map[? 27] = "i1" + string(i) + "j1" + string(3) + "i2" + string(i) + "j2" + string(2)
	hint_map[? 28] = "i1" + string(i) + "j1" + string(4) + "i2" + string(i) + "j2" + string(3)
	hint_map[? 29] = "i1" + string(i) + "j1" + string(5) + "i2" + string(i) + "j2" + string(4)
	hint_map[? 30] = "i1" + string(i) + "j1" + string(6) + "i2" + string(i) + "j2" + string(5)
	hint_map[? 31] = "i1" + string(i) + "j1" + string(7) + "i2" + string(i) + "j2" + string(6)
	i++
	hint_map[? 33] = "i1" + string(i) + "j1" + string(1) + "i2" + string(i) + "j2" + string(0)
	hint_map[? 34] = "i1" + string(i) + "j1" + string(2) + "i2" + string(i) + "j2" + string(1)
	hint_map[? 35] = "i1" + string(i) + "j1" + string(3) + "i2" + string(i) + "j2" + string(2)
	hint_map[? 36] = "i1" + string(i) + "j1" + string(4) + "i2" + string(i) + "j2" + string(3)
	hint_map[? 37] = "i1" + string(i) + "j1" + string(5) + "i2" + string(i) + "j2" + string(4)
	hint_map[? 38] = "i1" + string(i) + "j1" + string(6) + "i2" + string(i) + "j2" + string(5)
	hint_map[? 39] = "i1" + string(i) + "j1" + string(7) + "i2" + string(i) + "j2" + string(6)
	i++
	hint_map[? 41] = "i1" + string(i) + "j1" + string(1) + "i2" + string(i) + "j2" + string(0)
	hint_map[? 42] = "i1" + string(i) + "j1" + string(2) + "i2" + string(i) + "j2" + string(1)
	hint_map[? 43] = "i1" + string(i) + "j1" + string(3) + "i2" + string(i) + "j2" + string(2)
	hint_map[? 44] = "i1" + string(i) + "j1" + string(4) + "i2" + string(i) + "j2" + string(3)
	hint_map[? 45] = "i1" + string(i) + "j1" + string(5) + "i2" + string(i) + "j2" + string(4)
	hint_map[? 46] = "i1" + string(i) + "j1" + string(6) + "i2" + string(i) + "j2" + string(5)
	hint_map[? 47] = "i1" + string(i) + "j1" + string(7) + "i2" + string(i) + "j2" + string(6)
	i++
	hint_map[? 49] = "i1" + string(i) + "j1" + string(1) + "i2" + string(i) + "j2" + string(0)
	hint_map[? 50] = "i1" + string(i) + "j1" + string(2) + "i2" + string(i) + "j2" + string(1)
	hint_map[? 51] = "i1" + string(i) + "j1" + string(3) + "i2" + string(i) + "j2" + string(2)
	hint_map[? 52] = "i1" + string(i) + "j1" + string(4) + "i2" + string(i) + "j2" + string(3)
	hint_map[? 53] = "i1" + string(i) + "j1" + string(5) + "i2" + string(i) + "j2" + string(4)
	hint_map[? 54] = "i1" + string(i) + "j1" + string(6) + "i2" + string(i) + "j2" + string(5)
	hint_map[? 55] = "i1" + string(i) + "j1" + string(7) + "i2" + string(i) + "j2" + string(6)
	i++
	hint_map[? 57] = "i1" + string(i) + "j1" + string(1) + "i2" + string(i) + "j2" + string(0)
	hint_map[? 58] = "i1" + string(i) + "j1" + string(2) + "i2" + string(i) + "j2" + string(1)
	hint_map[? 59] = "i1" + string(i) + "j1" + string(3) + "i2" + string(i) + "j2" + string(2)
	hint_map[? 60] = "i1" + string(i) + "j1" + string(4) + "i2" + string(i) + "j2" + string(3)
	hint_map[? 61] = "i1" + string(i) + "j1" + string(5) + "i2" + string(i) + "j2" + string(4)
	hint_map[? 62] = "i1" + string(i) + "j1" + string(6) + "i2" + string(i) + "j2" + string(5)
	hint_map[? 63] = "i1" + string(i) + "j1" + string(7) + "i2" + string(i) + "j2" + string(6)
	
	/* VERTICAL (DOWN TO UP) */
	i = 1
	hint_map[? 72] = "i1" + string(i) + "j1" + string(0) + "i2" + string(i-1) + "j2" + string(0)
	hint_map[? 73] = "i1" + string(i) + "j1" + string(1) + "i2" + string(i-1) + "j2" + string(1)
	hint_map[? 74] = "i1" + string(i) + "j1" + string(2) + "i2" + string(i-1) + "j2" + string(2)
	hint_map[? 75] = "i1" + string(i) + "j1" + string(3) + "i2" + string(i-1) + "j2" + string(3)
	hint_map[? 76] = "i1" + string(i) + "j1" + string(4) + "i2" + string(i-1) + "j2" + string(4)
	hint_map[? 77] = "i1" + string(i) + "j1" + string(5) + "i2" + string(i-1) + "j2" + string(5)
	hint_map[? 78] = "i1" + string(i) + "j1" + string(6) + "i2" + string(i-1) + "j2" + string(6)
	hint_map[? 79] = "i1" + string(i) + "j1" + string(7) + "i2" + string(i-1) + "j2" + string(7)
	i++
	hint_map[? 80] = "i1" + string(i) + "j1" + string(0) + "i2" + string(i-1) + "j2" + string(0)
	hint_map[? 81] = "i1" + string(i) + "j1" + string(1) + "i2" + string(i-1) + "j2" + string(1)
	hint_map[? 82] = "i1" + string(i) + "j1" + string(2) + "i2" + string(i-1) + "j2" + string(2)
	hint_map[? 83] = "i1" + string(i) + "j1" + string(3) + "i2" + string(i-1) + "j2" + string(3)
	hint_map[? 84] = "i1" + string(i) + "j1" + string(4) + "i2" + string(i-1) + "j2" + string(4)
	hint_map[? 85] = "i1" + string(i) + "j1" + string(5) + "i2" + string(i-1) + "j2" + string(5)
	hint_map[? 86] = "i1" + string(i) + "j1" + string(6) + "i2" + string(i-1) + "j2" + string(6)
	hint_map[? 87] = "i1" + string(i) + "j1" + string(7) + "i2" + string(i-1) + "j2" + string(7)
	i++
	hint_map[? 88] = "i1" + string(i) + "j1" + string(0) + "i2" + string(i-1) + "j2" + string(0)
	hint_map[? 89] = "i1" + string(i) + "j1" + string(1) + "i2" + string(i-1) + "j2" + string(1)
	hint_map[? 90] = "i1" + string(i) + "j1" + string(2) + "i2" + string(i-1) + "j2" + string(2)
	hint_map[? 91] = "i1" + string(i) + "j1" + string(3) + "i2" + string(i-1) + "j2" + string(3)
	hint_map[? 92] = "i1" + string(i) + "j1" + string(4) + "i2" + string(i-1) + "j2" + string(4)
	hint_map[? 93] = "i1" + string(i) + "j1" + string(5) + "i2" + string(i-1) + "j2" + string(5)
	hint_map[? 94] = "i1" + string(i) + "j1" + string(6) + "i2" + string(i-1) + "j2" + string(6)
	hint_map[? 95] = "i1" + string(i) + "j1" + string(7) + "i2" + string(i-1) + "j2" + string(7)
	i++
	hint_map[? 96] = "i1" + string(i) + "j1" + string(0) + "i2" + string(i-1) + "j2" + string(0)
	hint_map[? 97] = "i1" + string(i) + "j1" + string(1) + "i2" + string(i-1) + "j2" + string(1)
	hint_map[? 98] = "i1" + string(i) + "j1" + string(2) + "i2" + string(i-1) + "j2" + string(2)
	hint_map[? 99] = "i1" + string(i) + "j1" + string(3) + "i2" + string(i-1) + "j2" + string(3)
	hint_map[? 100] = "i1" + string(i) + "j1" + string(4) + "i2" + string(i-1) + "j2" + string(4)
	hint_map[? 101] = "i1" + string(i) + "j1" + string(5) + "i2" + string(i-1) + "j2" + string(5)
	hint_map[? 102] = "i1" + string(i) + "j1" + string(6) + "i2" + string(i-1) + "j2" + string(6)
	hint_map[? 103] = "i1" + string(i) + "j1" + string(7) + "i2" + string(i-1) + "j2" + string(7)
	i++
	hint_map[? 104] = "i1" + string(i) + "j1" + string(0) + "i2" + string(i-1) + "j2" + string(0)
	hint_map[? 105] = "i1" + string(i) + "j1" + string(1) + "i2" + string(i-1) + "j2" + string(1)
	hint_map[? 106] = "i1" + string(i) + "j1" + string(2) + "i2" + string(i-1) + "j2" + string(2)
	hint_map[? 107] = "i1" + string(i) + "j1" + string(3) + "i2" + string(i-1) + "j2" + string(3)
	hint_map[? 108] = "i1" + string(i) + "j1" + string(4) + "i2" + string(i-1) + "j2" + string(4)
	hint_map[? 109] = "i1" + string(i) + "j1" + string(5) + "i2" + string(i-1) + "j2" + string(5)
	hint_map[? 110] = "i1" + string(i) + "j1" + string(6) + "i2" + string(i-1) + "j2" + string(6)
	hint_map[? 111] = "i1" + string(i) + "j1" + string(7) + "i2" + string(i-1) + "j2" + string(7)
	i++
	hint_map[? 112] = "i1" + string(i) + "j1" + string(0) + "i2" + string(i-1) + "j2" + string(0)
	hint_map[? 113] = "i1" + string(i) + "j1" + string(1) + "i2" + string(i-1) + "j2" + string(1)
	hint_map[? 114] = "i1" + string(i) + "j1" + string(2) + "i2" + string(i-1) + "j2" + string(2)
	hint_map[? 115] = "i1" + string(i) + "j1" + string(3) + "i2" + string(i-1) + "j2" + string(3)
	hint_map[? 116] = "i1" + string(i) + "j1" + string(4) + "i2" + string(i-1) + "j2" + string(4)
	hint_map[? 117] = "i1" + string(i) + "j1" + string(5) + "i2" + string(i-1) + "j2" + string(5)
	hint_map[? 118] = "i1" + string(i) + "j1" + string(6) + "i2" + string(i-1) + "j2" + string(6)
	hint_map[? 119] = "i1" + string(i) + "j1" + string(7) + "i2" + string(i-1) + "j2" + string(7)
	i++
	hint_map[? 120] = "i1" + string(i) + "j1" + string(0) + "i2" + string(i-1) + "j2" + string(0)
	hint_map[? 121] = "i1" + string(i) + "j1" + string(1) + "i2" + string(i-1) + "j2" + string(1)
	hint_map[? 122] = "i1" + string(i) + "j1" + string(2) + "i2" + string(i-1) + "j2" + string(2)
	hint_map[? 123] = "i1" + string(i) + "j1" + string(3) + "i2" + string(i-1) + "j2" + string(3)
	hint_map[? 124] = "i1" + string(i) + "j1" + string(4) + "i2" + string(i-1) + "j2" + string(4)
	hint_map[? 125] = "i1" + string(i) + "j1" + string(5) + "i2" + string(i-1) + "j2" + string(5)
	hint_map[? 126] = "i1" + string(i) + "j1" + string(6) + "i2" + string(i-1) + "j2" + string(6)
	hint_map[? 127] = "i1" + string(i) + "j1" + string(7) + "i2" + string(i-1) + "j2" + string(7)
	
	/* HORIZONTAL (LEFT TO RIGHT) */
	i = 0
	hint_map[? 128] = "i1" + string(i) + "j1" + string(0) + "i2" + string(i) + "j2" + string(1)
	hint_map[? 129] = "i1" + string(i) + "j1" + string(1) + "i2" + string(i) + "j2" + string(2)
	hint_map[? 130] = "i1" + string(i) + "j1" + string(2) + "i2" + string(i) + "j2" + string(3)
	hint_map[? 131] = "i1" + string(i) + "j1" + string(3) + "i2" + string(i) + "j2" + string(4)
	hint_map[? 132] = "i1" + string(i) + "j1" + string(4) + "i2" + string(i) + "j2" + string(5)
	hint_map[? 133] = "i1" + string(i) + "j1" + string(5) + "i2" + string(i) + "j2" + string(6)
	hint_map[? 134] = "i1" + string(i) + "j1" + string(6) + "i2" + string(i) + "j2" + string(7)
	i++
	hint_map[? 136] = "i1" + string(i) + "j1" + string(0) + "i2" + string(i) + "j2" + string(1)
	hint_map[? 137] = "i1" + string(i) + "j1" + string(1) + "i2" + string(i) + "j2" + string(2)
	hint_map[? 138] = "i1" + string(i) + "j1" + string(2) + "i2" + string(i) + "j2" + string(3)
	hint_map[? 139] = "i1" + string(i) + "j1" + string(3) + "i2" + string(i) + "j2" + string(4)
	hint_map[? 140] = "i1" + string(i) + "j1" + string(4) + "i2" + string(i) + "j2" + string(5)
	hint_map[? 141] = "i1" + string(i) + "j1" + string(5) + "i2" + string(i) + "j2" + string(6)
	hint_map[? 142] = "i1" + string(i) + "j1" + string(6) + "i2" + string(i) + "j2" + string(7)
	i++
	hint_map[? 144] = "i1" + string(i) + "j1" + string(0) + "i2" + string(i) + "j2" + string(1)
	hint_map[? 145] = "i1" + string(i) + "j1" + string(1) + "i2" + string(i) + "j2" + string(2)
	hint_map[? 146] = "i1" + string(i) + "j1" + string(2) + "i2" + string(i) + "j2" + string(3)
	hint_map[? 147] = "i1" + string(i) + "j1" + string(3) + "i2" + string(i) + "j2" + string(4)
	hint_map[? 148] = "i1" + string(i) + "j1" + string(4) + "i2" + string(i) + "j2" + string(5)
	hint_map[? 149] = "i1" + string(i) + "j1" + string(5) + "i2" + string(i) + "j2" + string(6)
	hint_map[? 150] = "i1" + string(i) + "j1" + string(6) + "i2" + string(i) + "j2" + string(7)
	i++
	hint_map[? 152] = "i1" + string(i) + "j1" + string(0) + "i2" + string(i) + "j2" + string(1)
	hint_map[? 153] = "i1" + string(i) + "j1" + string(1) + "i2" + string(i) + "j2" + string(2)
	hint_map[? 154] = "i1" + string(i) + "j1" + string(2) + "i2" + string(i) + "j2" + string(3)
	hint_map[? 155] = "i1" + string(i) + "j1" + string(3) + "i2" + string(i) + "j2" + string(4)
	hint_map[? 156] = "i1" + string(i) + "j1" + string(4) + "i2" + string(i) + "j2" + string(5)
	hint_map[? 157] = "i1" + string(i) + "j1" + string(5) + "i2" + string(i) + "j2" + string(6)
	hint_map[? 158] = "i1" + string(i) + "j1" + string(6) + "i2" + string(i) + "j2" + string(7)
	i++
	hint_map[? 160] = "i1" + string(i) + "j1" + string(0) + "i2" + string(i) + "j2" + string(1)
	hint_map[? 161] = "i1" + string(i) + "j1" + string(1) + "i2" + string(i) + "j2" + string(2)
	hint_map[? 162] = "i1" + string(i) + "j1" + string(2) + "i2" + string(i) + "j2" + string(3)
	hint_map[? 163] = "i1" + string(i) + "j1" + string(3) + "i2" + string(i) + "j2" + string(4)
	hint_map[? 164] = "i1" + string(i) + "j1" + string(4) + "i2" + string(i) + "j2" + string(5)
	hint_map[? 165] = "i1" + string(i) + "j1" + string(5) + "i2" + string(i) + "j2" + string(6)
	hint_map[? 166] = "i1" + string(i) + "j1" + string(6) + "i2" + string(i) + "j2" + string(7)
	i++
	hint_map[? 168] = "i1" + string(i) + "j1" + string(0) + "i2" + string(i) + "j2" + string(1)
	hint_map[? 169] = "i1" + string(i) + "j1" + string(1) + "i2" + string(i) + "j2" + string(2)
	hint_map[? 170] = "i1" + string(i) + "j1" + string(2) + "i2" + string(i) + "j2" + string(3)
	hint_map[? 171] = "i1" + string(i) + "j1" + string(3) + "i2" + string(i) + "j2" + string(4)
	hint_map[? 172] = "i1" + string(i) + "j1" + string(4) + "i2" + string(i) + "j2" + string(5)
	hint_map[? 173] = "i1" + string(i) + "j1" + string(5) + "i2" + string(i) + "j2" + string(6)
	hint_map[? 174] = "i1" + string(i) + "j1" + string(6) + "i2" + string(i) + "j2" + string(7)
	i++
	hint_map[? 176] = "i1" + string(i) + "j1" + string(0) + "i2" + string(i) + "j2" + string(1)
	hint_map[? 177] = "i1" + string(i) + "j1" + string(1) + "i2" + string(i) + "j2" + string(2)
	hint_map[? 178] = "i1" + string(i) + "j1" + string(2) + "i2" + string(i) + "j2" + string(3)
	hint_map[? 179] = "i1" + string(i) + "j1" + string(3) + "i2" + string(i) + "j2" + string(4)
	hint_map[? 180] = "i1" + string(i) + "j1" + string(4) + "i2" + string(i) + "j2" + string(5)
	hint_map[? 181] = "i1" + string(i) + "j1" + string(5) + "i2" + string(i) + "j2" + string(6)
	hint_map[? 182] = "i1" + string(i) + "j1" + string(6) + "i2" + string(i) + "j2" + string(7)
	i++
	hint_map[? 184] = "i1" + string(i) + "j1" + string(0) + "i2" + string(i) + "j2" + string(1)
	hint_map[? 185] = "i1" + string(i) + "j1" + string(1) + "i2" + string(i) + "j2" + string(2)
	hint_map[? 186] = "i1" + string(i) + "j1" + string(2) + "i2" + string(i) + "j2" + string(3)
	hint_map[? 187] = "i1" + string(i) + "j1" + string(3) + "i2" + string(i) + "j2" + string(4)
	hint_map[? 188] = "i1" + string(i) + "j1" + string(4) + "i2" + string(i) + "j2" + string(5)
	hint_map[? 189] = "i1" + string(i) + "j1" + string(5) + "i2" + string(i) + "j2" + string(6)
	hint_map[? 190] = "i1" + string(i) + "j1" + string(6) + "i2" + string(i) + "j2" + string(7)
	
	/* VERTICAL (UP TO DOWN) */
	i = 1
	hint_map[? 192] = "i1" + string(i-1) + "j1" + string(0) + "i2" + string(i) + "j2" + string(0)
	hint_map[? 193] = "i1" + string(i-1) + "j1" + string(1) + "i2" + string(i) + "j2" + string(1)
	hint_map[? 194] = "i1" + string(i-1) + "j1" + string(2) + "i2" + string(i) + "j2" + string(2)
	hint_map[? 195] = "i1" + string(i-1) + "j1" + string(3) + "i2" + string(i) + "j2" + string(3)
	hint_map[? 196] = "i1" + string(i-1) + "j1" + string(4) + "i2" + string(i) + "j2" + string(4)
	hint_map[? 197] = "i1" + string(i-1) + "j1" + string(5) + "i2" + string(i) + "j2" + string(5)
	hint_map[? 198] = "i1" + string(i-1) + "j1" + string(6) + "i2" + string(i) + "j2" + string(6)
	hint_map[? 199] = "i1" + string(i-1) + "j1" + string(7) + "i2" + string(i) + "j2" + string(7)
	i++
	hint_map[? 200] = "i1" + string(i-1) + "j1" + string(0) + "i2" + string(i) + "j2" + string(0)
	hint_map[? 201] = "i1" + string(i-1) + "j1" + string(1) + "i2" + string(i) + "j2" + string(1)
	hint_map[? 202] = "i1" + string(i-1) + "j1" + string(2) + "i2" + string(i) + "j2" + string(2)
	hint_map[? 203] = "i1" + string(i-1) + "j1" + string(3) + "i2" + string(i) + "j2" + string(3)
	hint_map[? 204] = "i1" + string(i-1) + "j1" + string(4) + "i2" + string(i) + "j2" + string(4)
	hint_map[? 205] = "i1" + string(i-1) + "j1" + string(5) + "i2" + string(i) + "j2" + string(5)
	hint_map[? 206] = "i1" + string(i-1) + "j1" + string(6) + "i2" + string(i) + "j2" + string(6)
	hint_map[? 207] = "i1" + string(i-1) + "j1" + string(7) + "i2" + string(i) + "j2" + string(7)
	i++
	hint_map[? 208] = "i1" + string(i-1) + "j1" + string(0) + "i2" + string(i) + "j2" + string(0)
	hint_map[? 209] = "i1" + string(i-1) + "j1" + string(1) + "i2" + string(i) + "j2" + string(1)
	hint_map[? 210] = "i1" + string(i-1) + "j1" + string(2) + "i2" + string(i) + "j2" + string(2)
	hint_map[? 211] = "i1" + string(i-1) + "j1" + string(3) + "i2" + string(i) + "j2" + string(3)
	hint_map[? 212] = "i1" + string(i-1) + "j1" + string(4) + "i2" + string(i) + "j2" + string(4)
	hint_map[? 213] = "i1" + string(i-1) + "j1" + string(5) + "i2" + string(i) + "j2" + string(5)
	hint_map[? 214] = "i1" + string(i-1) + "j1" + string(6) + "i2" + string(i) + "j2" + string(6)
	hint_map[? 215] = "i1" + string(i-1) + "j1" + string(7) + "i2" + string(i) + "j2" + string(7)
	i++
	hint_map[? 216] = "i1" + string(i-1) + "j1" + string(0) + "i2" + string(i) + "j2" + string(0)
	hint_map[? 217] = "i1" + string(i-1) + "j1" + string(1) + "i2" + string(i) + "j2" + string(1)
	hint_map[? 218] = "i1" + string(i-1) + "j1" + string(2) + "i2" + string(i) + "j2" + string(2)
	hint_map[? 219] = "i1" + string(i-1) + "j1" + string(3) + "i2" + string(i) + "j2" + string(3)
	hint_map[? 220] = "i1" + string(i-1) + "j1" + string(4) + "i2" + string(i) + "j2" + string(4)
	hint_map[? 221] = "i1" + string(i-1) + "j1" + string(5) + "i2" + string(i) + "j2" + string(5)
	hint_map[? 222] = "i1" + string(i-1) + "j1" + string(6) + "i2" + string(i) + "j2" + string(6)
	hint_map[? 223] = "i1" + string(i-1) + "j1" + string(7) + "i2" + string(i) + "j2" + string(7)
	i++
	hint_map[? 224] = "i1" + string(i-1) + "j1" + string(0) + "i2" + string(i) + "j2" + string(0)
	hint_map[? 225] = "i1" + string(i-1) + "j1" + string(1) + "i2" + string(i) + "j2" + string(1)
	hint_map[? 226] = "i1" + string(i-1) + "j1" + string(2) + "i2" + string(i) + "j2" + string(2)
	hint_map[? 227] = "i1" + string(i-1) + "j1" + string(3) + "i2" + string(i) + "j2" + string(3)
	hint_map[? 228] = "i1" + string(i-1) + "j1" + string(4) + "i2" + string(i) + "j2" + string(4)
	hint_map[? 229] = "i1" + string(i-1) + "j1" + string(5) + "i2" + string(i) + "j2" + string(5)
	hint_map[? 230] = "i1" + string(i-1) + "j1" + string(6) + "i2" + string(i) + "j2" + string(6)
	hint_map[? 231] = "i1" + string(i-1) + "j1" + string(7) + "i2" + string(i) + "j2" + string(7)
	i++
	hint_map[? 232] = "i1" + string(i-1) + "j1" + string(0) + "i2" + string(i) + "j2" + string(0)
	hint_map[? 233] = "i1" + string(i-1) + "j1" + string(1) + "i2" + string(i) + "j2" + string(1)
	hint_map[? 234] = "i1" + string(i-1) + "j1" + string(2) + "i2" + string(i) + "j2" + string(2)
	hint_map[? 235] = "i1" + string(i-1) + "j1" + string(3) + "i2" + string(i) + "j2" + string(3)
	hint_map[? 236] = "i1" + string(i-1) + "j1" + string(4) + "i2" + string(i) + "j2" + string(4)
	hint_map[? 237] = "i1" + string(i-1) + "j1" + string(5) + "i2" + string(i) + "j2" + string(5)
	hint_map[? 238] = "i1" + string(i-1) + "j1" + string(6) + "i2" + string(i) + "j2" + string(6)
	hint_map[? 239] = "i1" + string(i-1) + "j1" + string(7) + "i2" + string(i) + "j2" + string(7)
	i++
	hint_map[? 240] = "i1" + string(i-1) + "j1" + string(0) + "i2" + string(i) + "j2" + string(0)
	hint_map[? 241] = "i1" + string(i-1) + "j1" + string(1) + "i2" + string(i) + "j2" + string(1)
	hint_map[? 242] = "i1" + string(i-1) + "j1" + string(2) + "i2" + string(i) + "j2" + string(2)
	hint_map[? 243] = "i1" + string(i-1) + "j1" + string(3) + "i2" + string(i) + "j2" + string(3)
	hint_map[? 244] = "i1" + string(i-1) + "j1" + string(4) + "i2" + string(i) + "j2" + string(4)
	hint_map[? 245] = "i1" + string(i-1) + "j1" + string(5) + "i2" + string(i) + "j2" + string(5)
	hint_map[? 246] = "i1" + string(i-1) + "j1" + string(6) + "i2" + string(i) + "j2" + string(6)
	hint_map[? 247] = "i1" + string(i-1) + "j1" + string(7) + "i2" + string(i) + "j2" + string(7)
}